// Generated by @hypernym/nuxt-gsap
import { Plugin } from '#app';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ScrollToPlugin } from 'gsap/ScrollToPlugin';
declare const plugin: Plugin<{
  gsap: typeof gsap;
  ScrollTrigger: typeof ScrollTrigger;
ScrollToPlugin: typeof ScrollToPlugin;
}>;
export default plugin;